-- ============================================
-- V1: Initial schema for Academy Management System
-- ============================================

-- USERS
CREATE TABLE users (
    id         NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    password   VARCHAR2(255 CHAR) NOT NULL,
    email      VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    role       VARCHAR2(255 CHAR) NOT NULL CHECK (role IN ('ADMIN','COACH','STUDENT'))
);

-- BATCHES
CREATE TABLE batches (
    id         NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR2(255 CHAR) NOT NULL,
    schedule   VARCHAR2(255 CHAR) NOT NULL
);

-- COACHES
CREATE TABLE coaches (
    id               NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          NUMBER(19,0) NOT NULL UNIQUE,
    specialization   VARCHAR2(255 CHAR),
    bio              VARCHAR2(1000 CHAR),
    CONSTRAINT fk_coaches_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- STUDENTS
CREATE TABLE students (
    id                       NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                  NUMBER(19,0) NOT NULL UNIQUE,
    parent_contact_number    VARCHAR2(255 CHAR),
    CONSTRAINT fk_students_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- COACH_BATCH_ASSIGNMENTS
CREATE TABLE coach_batch_assignments (
    id             NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coach_id       NUMBER(19,0) NOT NULL,
    batch_id       NUMBER(19,0) NOT NULL,
    assigned_date  DATE NOT NULL,
    CONSTRAINT fk_cba_coach FOREIGN KEY (coach_id) REFERENCES coaches(id),
    CONSTRAINT fk_cba_batch FOREIGN KEY (batch_id) REFERENCES batches(id),
    CONSTRAINT uk_cba_coach_batch UNIQUE (coach_id, batch_id)
);

-- STUDENT_BATCH_ASSIGNMENTS
CREATE TABLE student_batch_assignments (
    id             NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id     NUMBER(19,0) NOT NULL,
    batch_id       NUMBER(19,0) NOT NULL,
    assigned_date  DATE NOT NULL,
    CONSTRAINT fk_sba_student FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT fk_sba_batch FOREIGN KEY (batch_id) REFERENCES batches(id),
    CONSTRAINT uk_sba_student_batch UNIQUE (student_id, batch_id)
);

-- COACH_REQUESTS
CREATE TABLE coach_requests (
    id               NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          NUMBER(19,0) NOT NULL,
    specialization   VARCHAR2(255 CHAR),
    bio              VARCHAR2(1000 CHAR),
    status           VARCHAR2(255 CHAR) NOT NULL CHECK (status IN ('PENDING','APPROVED','REJECTED')),
    requested_at     TIMESTAMP NOT NULL,
    reviewed_at      TIMESTAMP,
    remarks          VARCHAR2(255 CHAR),
    CONSTRAINT fk_coach_req_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- STUDENT_BATCH_REQUESTS
CREATE TABLE student_batch_requests (
    id                       NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                  NUMBER(19,0) NOT NULL,
    batch_id                 NUMBER(19,0) NOT NULL,
    parent_contact_number    VARCHAR2(255 CHAR),
    status                   VARCHAR2(255 CHAR) NOT NULL CHECK (status IN ('PENDING','APPROVED','REJECTED')),
    requested_at             TIMESTAMP NOT NULL,
    reviewed_at              TIMESTAMP,
    remarks                  VARCHAR2(255 CHAR),
    CONSTRAINT fk_sbr_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_sbr_batch FOREIGN KEY (batch_id) REFERENCES batches(id)
);

-- ATTENDANCE
CREATE TABLE attendance (
    id                    NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id            NUMBER(19,0) NOT NULL,
    batch_id              NUMBER(19,0) NOT NULL,
    attendance_date       DATE NOT NULL,
    status                VARCHAR2(255 CHAR) NOT NULL CHECK (status IN ('PRESENT','ABSENT','LATE')),
    marked_by_coach_id    NUMBER(19,0) NOT NULL,
    CONSTRAINT fk_att_student FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT fk_att_batch FOREIGN KEY (batch_id) REFERENCES batches(id),
    CONSTRAINT fk_att_coach FOREIGN KEY (marked_by_coach_id) REFERENCES coaches(id),
    CONSTRAINT uk_att_student_batch_date UNIQUE (student_id, batch_id, attendance_date)
);

-- PERFORMANCE_RATINGS
CREATE TABLE performance_ratings (
    id            NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id    NUMBER(19,0) NOT NULL,
    batch_id      NUMBER(19,0) NOT NULL,
    coach_id      NUMBER(19,0) NOT NULL,
    rating        NUMBER(10,0) NOT NULL,
    remarks       VARCHAR2(1000 CHAR),
    rated_date    DATE NOT NULL,
    CONSTRAINT fk_pr_student FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT fk_pr_batch FOREIGN KEY (batch_id) REFERENCES batches(id),
    CONSTRAINT fk_pr_coach FOREIGN KEY (coach_id) REFERENCES coaches(id)
);

-- STUDENT_FEEDBACK
CREATE TABLE student_feedback (
    id                  NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id          NUMBER(19,0) NOT NULL,
    coach_id            NUMBER(19,0) NOT NULL,
    feedback_comment    VARCHAR2(2000 CHAR) NOT NULL,
    submitted_at        TIMESTAMP NOT NULL,
    CONSTRAINT fk_sf_student FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT fk_sf_coach FOREIGN KEY (coach_id) REFERENCES coaches(id)
);

-- COACH_FEEDBACK
CREATE TABLE coach_feedback (
    id                  NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id          NUMBER(19,0) NOT NULL,
    coach_id            NUMBER(19,0) NOT NULL,
    feedback_comment    VARCHAR2(2000 CHAR) NOT NULL,
    visibility          VARCHAR2(255 CHAR) NOT NULL CHECK (visibility IN ('STUDENT_VISIBLE','ADMIN_ONLY')),
    submitted_at        TIMESTAMP NOT NULL,
    CONSTRAINT fk_cf_student FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT fk_cf_coach FOREIGN KEY (coach_id) REFERENCES coaches(id)
);